FEWSHOT_PROMPT:
  # NOTE: change these keys to match the data keys in your training data. 
  key_class: class-unaliased-id511.dist6
  key_utility: utility-unaliased-id511.dist6
  key_affordance: affordance-unaliased-id511.dist6
  key_ooe: ooe-unaliased-id511.dist6
  destination_folder: ./

EVAL:
  few_shot_prompt_file_path: /path_to_few_shot_prompt/
  results_folder: ./logs